plugins {
    id 'com.android.application'
    id 'com.hyperdevs.poeditor'
}

android {
    compileSdk 35

    defaultConfig {
        applicationId "cf.tenseventyseven.fresh"
        minSdk 34
        //noinspection ExpiredTargetSdkVersion
        targetSdk 28
        versionCode 25060201
        versionName "6.0.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    namespace 'cf.tenseventyseven.fresh'
}

// POEditor Config - only import when file exists
if (file('../../poeditor.gradle').exists()) {
    apply from: '../../poeditor.gradle'
}

dependencies {
    implementation "sesl.androidx.core:core:1.15.0+1.0.11-sesl6+rev0"
    implementation "sesl.androidx.appcompat:appcompat:1.7.0+1.0.34-sesl6+rev8"
    implementation "sesl.androidx.preference:preference:1.2.1+1.0.4-sesl6+rev3"

    implementation "sesl.com.google.android.material:material:1.12.0+1.0.23-sesl6+rev3"
    implementation 'com.github.rubensousa:gravitysnaphelper:2.2.2'

    // Markwon
    implementation "io.noties.markwon:core:4.6.2"

    // One UI Design Library
    implementation "io.github.tribalfs:oneui-design:0.6.0+oneui6"
    implementation "io.github.oneuiproject:icons:1.1.0"

    implementation "com.jakewharton:butterknife:10.2.3"
    annotationProcessor "com.jakewharton:butterknife-compiler:10.2.3"

    // Fetch
    implementation "com.github.tonyofrancis.Fetch:fetch2:3.4.1"

    // Lottie
    implementation "com.airbnb.android:lottie:5.2.0"

    // Picasso
    implementation 'com.squareup.picasso:picasso:2.71828'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}

configurations.implementation {
    exclude (group:"androidx.core",  module:"core")
    exclude (group:"androidx.core",  module:"core-ktx")
    exclude (group:"androidx.customview",  module:"customview")
    exclude (group:"androidx.coordinatorlayout",  module:"coordinatorlayout")
    exclude (group:"androidx.drawerlayout",  module:"drawerlayout")
    exclude (group:"androidx.viewpager2",  module:"viewpager2")
    exclude (group:"androidx.viewpager",  module:"viewpager")
    exclude (group:"androidx.appcompat", module:"appcompat")
    exclude (group:"androidx.fragment", module:"fragment")
    exclude (group:"androidx.preference",  module:"preference")
    exclude (group:"androidx.recyclerview", module:"recyclerview")
    exclude (group:"androidx.slidingpanelayout",  module:"slidingpanelayout")
    exclude (group:"androidx.swiperefreshlayout",  module:"swiperefreshlayout")
    exclude (group:"com.google.android.material", module: "material")
}